jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: ${JENKINS_ADMIN_ID}
         password: ${JENKINS_ADMIN_PASSWORD}

  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Job/Build:dev"
        - "Job/Cancel:dev"
        - "Job/Workspace:dev"
        - "Job/Read:dev"
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
        - "Overall/Manage:authenticated"
        - "Run/Replay:dev"
        - "Run/Update:dev"
  numExecutors: 1
  remotingSecurity:
    enabled: true

security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy

unclassified:
  location:
    url: http://localhost:8080/

jobs:
  - script: >
      organizationFolder('github-2TDST') {
          description("Slashicorp organizational project")
          displayName('Github/jenkins-automate-docker')
          organizations {
              github {
                  repoOwner('2TDST')
                  apiUri('https://api.github.com')
              }
          }
          projectFactories {
              workflowMultiBranchProjectFactory {
                  // Relative location within the checkout of your Pipeline script.
                  scriptPath('jenkins-automate-docker.Jenkinsfile')
              }
          }
          orphanedItemStrategy {
              discardOldItems {
                  daysToKeep(1)
                  numToKeep(2)
              }
          }