---
apiVersion: v1
kind: Service
metadata:
  name: dimdim-api-svc
  labels:
    app: dimdim-api-svc
spec:
  type: NodePort
  selector:
    app: dimdim-api-svc
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dimdim-api
  labels:
    app: dimdim-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dimdim-api
  template:
    metadata:
      labels:
        app: dimdim-api
    spec:
      containers:
        - name: dimdim-api
          image: slashicorp/dimdim:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - secretRef:
                name: mysql-secret
---