---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  type: NodePort
  ports:
    - port: 3306
  selector:
    app: mysql
    tier: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
      tier: mysql
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
        tier: mysql
    spec:
      containers:
        - image: mysql:5.7
          name: mysql
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - secretRef:
                name: mysql-secret
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
    app: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  # DEFAULT MYSQL VARIABLES
  MYSQL_USER: root
  MYSQL_PASSWORD: v3dIPeNiga2
  MYSQL_DATABASE: ag_dimdim_db
  MYSQL_ROOT_PASSWORD: v3dIPeNiga2
  # API APP VARIABLES
  DB_HOST: mysql
  DB_DRIVER: mysql
  DB_USER: root
  DB_PASSWORD: v3dIPeNiga2
  DB_NAME: ag_dimdim_db
  DB_PORT: "3306"
---
